django-madusonovidiusscrumy/madusonovidiusscrumy/urls.py
#Django
from django.urls import path, include

#Local
from . import views

urlpatterns = [
    #path('', views.get_grading_parameters, name='get_grading_parameters'),
    path('movegoal/<int:goal_id>/', views.move_goal, name='move_goal'),
    path('addgoal', views.add_goal, name='add_goal'),
    path('home', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls'))

]

madusonovidiusscrumy/urls.py
#Django
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#Local
from . import views

app_name = 'madusonovidiusscrumy'

urlpatterns = [
    #path('', views.get_grading_parameters, name='get_grading_parameters'),
    path('movegoal/<int:goal_id>', views.move_goal, name='movegoal'),
    path('addgoal/', views.add_goal, name='addgoal'),
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('index/', views.index, name='index'),
    path('welcome', views.welcome, name='welcome')
]

urlpatterns += staticfiles_urlpatterns()

myscrumy/urls.py
# Django
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('madusonovidiusscrumy/', include('madusonovidiusscrumy.urls')),
    path('websocket/', include('websocket.urls')),
    # path('index/', include('madusonovidiusscrumy.urls',
    # namespace='madusonovidiusscrumy'))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

django-madusonovidiusscrumy/madusonovidiusscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class GoalStatus(models.Model):
    status_name = models.CharField(max_length=50)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=50)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length=50)
    moved_by = models.CharField(max_length=50)
    owner = models.CharField(max_length=50)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT,)
    user = models.ForeignKey(User,
                             related_name='goal_created',
                             on_delete=models.PROTECT,)

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)
    moved_from = models.CharField(max_length=50)
    moved_to = models.CharField(max_length=50)
    time_of_action = models.DateTimeField(timezone.now)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.CASCADE)

    def __str__(self):
        return self.created_by

madusonovidiusscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.forms import ModelForm, CharField, widgets, PasswordInput


# Create your models here.
class GoalStatus(models.Model):
    status_name = models.CharField(max_length=50)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=50)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length=50)
    moved_by = models.CharField(max_length=50)
    owner = models.CharField(max_length=50)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT,)
    user = models.ForeignKey(User,
                             related_name='created_by',
                             on_delete=models.PROTECT,)

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)
    moved_from = models.CharField(max_length=50)
    moved_to = models.CharField(max_length=50)
    time_of_action = models.DateTimeField(timezone.now)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.CASCADE)

    def __str__(self):
        return self.created_by


class SignupForm(ModelForm):
    password = CharField(widget=PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']
        permissions = (
            ("can_create_personal_weekly", "Create Personal Weekly Goal"),
        )



class MoveGoalForm(ModelForm):
    goal_name = CharField(disabled=True)
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'goal_status']

django-madusonovidiusscrumy/madusonovidiusscrumy/views.py
# Standard library
from random import randint

# Django
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import render

# Local
from madusonovidiusscrumy.models import *

# def get_grading_parameters(request):
# response = ScrumyGoals.objects.filter(goal_name__exact='Learn Django')
# return HttpResponse(response)


def move_goal(request, goal_id):
    message = {'error': 'A record with that goal id does not exist'}
    try:
        obj = ScrumyGoals.objects.get(id=goal_id)
    except Exception as e:
        return render(request, 'madusonovidiusscrumy/exception.html', message)
    else:
        return HttpResponse(obj.goal_name)


def add_goal(request):
    already_used = []
    number = randint(1000, 9999)
    if number not in already_used:
        addgoal = ScrumyGoals.objects.create(goal_name='Keep Learning Django',
                                             goal_id=number,
                                             created_by='Louis',
                                             moved_by='Louis', owner='Louis',
                                             goal_status=GoalStatus.objects.get
                                             (status_name='Weekly Goal'),
                                             user=User.objects.get(
                                                 username='Louis Oma')
                                             )
        already_used.append(number)
        return HttpResponse(addgoal)


def home(request):
    scrumygoals = ScrumyGoals.objects.all()
    dictionary = {
        'scrumygoals': scrumygoals

    }
    return render(request, 'madusonovidiusscrumy/home.html', dictionary)

# Create your views here.

madusonovidiusscrumy/views.py
# Standard library
from random import randint

# Django
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404

# Local
from madusonovidiusscrumy.models import *
from .decorators import allowed_users


# def get_grading_parameters(request):
# response = ScrumyGoals.objects.filter(goal_name__exact='Learn Django')
# return HttpResponse(response)


@login_required
def move_goal(request, goal_id):
    """message = {'error': 'A record with that goal id does not exist'}
    try:
        obj = ScrumyGoals.objects.get(goal_id=goal_id)
    except Exception as e:
        return render(request, 'exception.html', message)
    else:
        return HttpResponse(obj.goal_name)"""
    user = request.user
    goal = get_object_or_404(ScrumyGoals, goal_id=goal_id)
    if User.objects.filter(username=user, groups__name='Developer').exists():
        if request.method == 'POST':
            form = MoveGoalForm(request.POST, instance=goal)
            if goal.user == request.user:
                if form.is_valid():
                    if GoalStatus.objects.get(
                            status_name='Done Goal') != goal.goal_status:
                        form.save()
                        return redirect('madusonovidiusscrumy:home')
                    else:
                        messages.error(
                            request,
                            "Your group policy doesn't permit this operation"
                        )
            else:
                messages.error(request, "You cannot move this goal")
        else:
            form = MoveGoalForm(instance=goal)
        return render(request, 'movegoal.html',
                      {'form': form, 'post': goal})

    elif User.objects.filter(username=user,
                             groups__name='Quality Assurance').exists():
        if request.method == 'POST':
            form = MoveGoalForm(request.POST, instance=goal)
            if goal.user != request.user:
                if GoalStatus.objects.get(
                        status_name='Verify Goal') == goal.goal_status:
                    if form.is_valid():
                        if GoalStatus.objects.get(
                                status_name='Verify Goal') != goal.goal_status \
                                and GoalStatus.objects.get(
                                status_name='Done Goal') != goal.goal_status:
                            messages.error(request,
                                           'You cannot perform this operation')
                        else:
                            form.save()
                            return redirect('madusonovidiusscrumy:home')
                else:
                    messages.error(request, 'You can only move a verified goal for this user')
            elif goal.user == request.user:
                if form.is_valid():
                    if GoalStatus.objects.get(
                            status_name='Weekly Goal') == goal.goal_status:
                        messages.error(request,
                                       'You cannot perform this operation')
                    else:
                        form.save()
                        return redirect('madusonovidiusscrumy:home')
        else:
            form = MoveGoalForm(instance=goal)
        return render(request, 'movegoal.html',
                      {'form': form, 'post': goal})

    elif User.objects.filter(username=user, groups__name='Admin').exists():
        if request.method == 'POST':
            form = MoveGoalForm(request.POST, instance=goal)
            if form.is_valid():
                goal.save()
                return redirect('madusonovidiusscrumy:home')
        else:
            form = MoveGoalForm(instance=goal)
        return render(request, 'movegoal.html',
                      {'form': form, 'post': goal})

    elif User.objects.filter(username=user, groups__name='Owner').exists():
        if request.method == 'POST':
            form = MoveGoalForm(request.POST, instance=goal)
            if goal.user == request.user:
                if form.is_valid():
                    goal = form.save(commit=False)
                    goal.save()
                    return redirect('madusonovidiusscrumy:home')
            else:
                messages.info(request, 'You cannot perform this operation')
        else:
            form = MoveGoalForm(instance=goal)
        return render(request, 'movegoal.html',
                      {'form': form, 'post': goal})


@login_required
@allowed_users(allowed_roles=['Quality Assurance', 'Developer', 'Owner'])
def add_goal(request):
    user = request.user
    already_used = []
    number = randint(1000, 9999)
    form = CreateGoalForm()
    if number not in already_used:
        form = CreateGoalForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            if instance.user == request.user:
                instance.goal_status = get_object_or_404(GoalStatus,
                                                         status_name='Weekly Goal')
                instance.goal_id = number
                already_used.append(number)
                instance.save()
                return redirect('madusonovidiusscrumy:home')
            else:
                messages.info(request,
                              'You cannot create a goal for this user')
    return render(request, 'madusonovidiusscrumy/addgoal.html', {'form': form})


@login_required
def home(request):
    scrumygoals = ScrumyGoals.objects.all()
    user = User.objects.all()
    dictionary = {
        'users': user,
        'scrumygoals': scrumygoals
    }
    return render(request, 'home.html', dictionary)


def index(request):
    groups = Group.objects.get(name='Developer')
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.is_superuser = True
            user.is_staff = True
            user.save()
            groups.user_set.add(user)

            return redirect('madusonovidiusscrumy:welcome')

    else:
        form = SignupForm()

    return render(request, 'index.html', {'form': form})


def welcome(request):
    dictionary = {
        'welcome': 'Your account has been successfully created'
    }
    return render(request, 'welcome.html', dictionary)

madusonovidiusscrumy/templates/madusonovidiusscrumy/addgoal.html
{% load static %}
<link href="{% static 'madusonovidiusscrumy/../../static/styles.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'materialize/js/materialize.min.js' %}" type="text/javascript"></script>

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add Goal">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
</form>

madusonovidiusscrumy/templates/madusonovidiusscrumy/base.html
{% load static%}
<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}" media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>

      <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
    </body>
  </html>

madusonovidiusscrumy/templates/madusonovidiusscrumy/home.html
{% load static %}
<link href="/static/styles.css" rel="stylesheet" type="text/css">


<div id="header">
    <a href="{% url 'madusonovidiusscrumy:home' %}"><h1 style="font-size: inherit">SCRUMY GOALS</h1></a>
<div id="user-tools">
    {% if user.is_authenticated %}
       Hello, {{ user.get_username.title }}./ You are logged in as {{ user.groups.get }}/
       <a href="{% url 'logout'%}">Logout</a>
   {% else %}
       <a href="{% url 'login'%}?next={{request.path}}">Login</a>
   {% endif %}
</div>
  </div>

<table>
{% csrf_token %}
        <tr>
        <th>User</th>
        <th>Weekly Goals</th>
        <th>Daily Goals</th>
        <th>Verify Goals</th>
        <th>Done Goals</th>
        </tr>

        {% for user in users %}
        <tr>
            <td><b>{{ user.username.title }}: {{ user.groups.get }}</b></td>


            <td>
            {% for goal in user.created_by.all %}
                {% if goal.goal_status.status_name == 'Weekly Goal' %}
                    <a href="{% url 'madusonovidiusscrumy:movegoal' goal.goal_id %}">{{ goal.goal_name }}:<b>{{ goal.goal_id }}</b></a><br>
                {% endif %}
            {% endfor %}
            </td>

            <td>
            {% for goal in user.created_by.all %}
                {% if goal.goal_status.status_name == 'Daily Goal' %}
               <a href="{% url 'madusonovidiusscrumy:movegoal' goal.goal_id %}">{{ goal.goal_name }}:<b>{{ goal.goal_id }}</b></a><br>
                {% endif %}
                {% endfor %}
            </td>

            <td>
            {% for goal in user.created_by.all %}
                {% if goal.goal_status.status_name == 'Verify Goal' %}
                    <a href="{% url 'madusonovidiusscrumy:movegoal' goal.goal_id %}">{{ goal.goal_name }}:<b>{{ goal.goal_id }}</b></a><br>
                {% endif %}
                {% endfor %}
            </td>

            <td>
            {% for goal in user.created_by.all %}
                {% if goal.goal_status.status_name == 'Done Goal' %}
                <a href="{% url 'madusonovidiusscrumy:movegoal' goal.goal_id %}">{{ goal.goal_name }}:<b>{{ goal.goal_id }}</b></a><br>
                {% endif %}
                {% endfor %}
            </td>
        </tr>
        {% endfor %}

</table>

<a href="{% url 'madusonovidiusscrumy:addgoal' %}"> Click Here to Add a new Goal</a>

madusonovidiusscrumy/templates/madusonovidiusscrumy/index.html
{% load static %}
<link href="{% static 'madusonovidiusscrumy/../../static/styles.css' %}" rel="stylesheet" type="text/css">

     <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create Account">
    </form>

<a href="{% url 'madusonovidiusscrumy:addgoal' %}">Add Goals</a><br>
<a href="{% url 'login' %}">Already have an account? Login Here</a>

madusonovidiusscrumy/templates/madusonovidiusscrumy/movegoal.html
{% load static %}
<link href="{% static 'styles.css' %}" rel="stylesheet" type="text/css"/>
<script src="{% static 'materialize/js/materialize.min.js' %}" type="text/javascript"></script>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Move Goal">
   {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
</form>
</div>

madusonovidiusscrumy/templates/madusonovidiusscrumy/user_error.html
<p>You are not allowed to view this page</p>

madusonovidiusscrumy/templates/madusonovidiusscrumy/welcome.html
<h1>
    {{ welcome }}
</h1>

<h3><a href="{% url 'madusonovidiusscrumy:login' %}">Login</a></h3>